CREATE TABLE TRANSFERENCIA (
    ID int generated always as identity not null,
    PRODUTO_ID int not null,
    QUANTIDADE int not null,
    ESTOQUE_ORIGEM_ID int not null,
    ESTOQUE_DESTINO_ID int not null,
    DATA_HORA_TRANSFERENCIA timestamp not null,
    RESPONSAVEL varchar not null,
    MOTIVO varchar not null,
    MOVIMENTACAO_SAIDA_ID int,
    MOVIMENTACAO_ENTRADA_ID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID),
    FOREIGN KEY (ESTOQUE_ORIGEM_ID) REFERENCES ESTOQUE(ID),
    FOREIGN KEY (ESTOQUE_DESTINO_ID) REFERENCES ESTOQUE(ID),
    FOREIGN KEY (MOVIMENTACAO_SAIDA_ID) REFERENCES MOVIMENTACAO(ID),
    FOREIGN KEY (MOVIMENTACAO_ENTRADA_ID) REFERENCES MOVIMENTACAO(ID)
);

